Frontend
ConstellationApps/DeviceManager pull request #1
Opened 2017-02-15 05:17 UTC by m-wynn

Pls test

2017-02-15 08:14 UTC, the-maldridge requested changes
A few small issues in the models, but other than that this checks out OK.

2017-02-15 08:14 UTC, the-maldridge commented on constellation_devicemanager/models.py
> +                regex='^([0-9A-Fa-f]{2}[:-]?){5}([0-9A-Fa-f]{2})$',
This regex should exactly match the export format specified by the netaddr custom formatter in views.py

2017-02-15 08:14 UTC, the-maldridge commented on constellation_devicemanager/models.py
> +                message='Not a MAC address',
This message should include a remark that it is not a properly formatted MAC address as it might still be a valid, improperly formatted one.

2017-02-15 19:56 UTC, m-wynn commented on constellation_devicemanager/models.py
> +                regex='^([0-9A-Fa-f]{2}[:-]?){5}([0-9A-Fa-f]{2})$',
Resolved and force-pushed.

2017-02-15 22:09 UTC, the-maldridge commented
Delete does not seem to work.

2017-02-15 22:13 UTC, m-wynn commented
Fixed delete

2017-02-16 02:52 UTC, the-maldridge approved these changes

2017-02-16 02:52 UTC, merged